# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest poetry codespell cpplint poethepoet isort
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
    - name: Lint with isort
      run: |
        poe isort

    - name: Lint with isort
      run: |
        poe isort

    - name: Lint with flake8 for .py
      run: |
        poe flake8-py

    - name: Lint with flake8 for .pyx
      run: |
        poe flake8-pyx

    - name: Lint with cpplint
      run: |
        poe cpplint
